### ISSUE TITLE
动画效果资讯

### ISSUE THREAD

**Issue by bcrystalest** [wjTime/WJDropDownMenu#6]
点击出现下拉菜单的时候是有动画的,可是点击菜单消失的时候是没有动画的,而且菜单展开收起的动画时间在哪里设置呢

**Comment by wjTime** [comment]
稍等 我看看

**Comment by wjTime** [comment]
有动画呀

**Comment by wjTime** [comment]
menu.caverAnimationTime = 0.2;             //  增加了遮盖层动画时间设置   不设置默认是  0.15 这是动画时间

**Comment by bcrystalest** [comment]
额找到了遮盖动画,谢谢,但是我点击了菜单标题出现下拉内容然后再点击一次标题下拉内容消失,消失时的动画的时间设置在哪呀

**Comment by wjTime** [comment]
消失的时间和 展开的时间是一样的 要单独吗？

**Comment by wjTime** [comment]
要的我现在就加进去

**Comment by wjTime** [comment]
消失的时间没有设置 我设置下

**Comment by bcrystalest** [comment]
额最好能加一下,谢谢啦

**Comment by wjTime** [comment]
恩 在加 马上

**Comment by wjTime** [comment]
menu.hideAnimationTime = 0.2;              //  增加了缩进动画时间设置   不设置默认是  0.15  加进去啦

**Comment by bcrystalest** [comment]
okok,那我是要重新Down一份了
